# Generated by Django 2.2 on 2019-06-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
