# Generated by Django 2.2 on 2019-06-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190606_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='changing_room',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='field',
            name='parking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='field',
            name='shower',
            field=models.BooleanField(default=True),
        ),
    ]
