# Generated by Django 2.2 on 2019-06-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190606_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='field',
            name='changing_room',
            field=models.BooleanField(default=True, verbose_name='Раздевалка'),
        ),
        migrations.AlterField(
            model_name='field',
            name='close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='закрытие'),
        ),
        migrations.AlterField(
            model_name='field',
            name='open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='открытие'),
        ),
        migrations.AlterField(
            model_name='field',
            name='parking',
            field=models.BooleanField(default=True, verbose_name='Парковка'),
        ),
        migrations.AlterField(
            model_name='field',
            name='shower',
            field=models.BooleanField(default=True, verbose_name='Душ'),
        ),
        migrations.AlterField(
            model_name='field',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название поля'),
        ),
    ]
