# Generated by Django 2.2.1 on 2019-05-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_field_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
