# Generated by Django 2.2 on 2019-06-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20190606_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['create_date']},
        ),
    ]
