# Generated by Django 2.2 on 2019-06-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20190608_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={},
        ),
    ]
