# Generated by Django 2.2 on 2019-06-08 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20190608_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
